### ISSUE TITLE
does not parse non html tags (The exit status '1' says something wen wrong)

### ISSUE THREAD

**Issue by balvirsingh** [stedekay/SpraedPDFGeneratorBundle#24]
if in content there is non html tags then it gives error like 

The exit status code '1' says something went wrong:
stderr: "line 21 column 54 - Error: <test> is not recognized!
line 68 column 34 - Error: <djweijsenfeld> is not recognized!
line 85 column 44 - Error: <x-apple-data-detectors:> is not recognized!
line 87 column 23 - Error: tel:0174 is not recognized!

<test> , <djweijsenfeld> etc are not html tags thats why its gives error but if on dompdf or tcpdf its working fine. Only problem with your bundle.

![snapshot5](https://cloud.githubusercontent.com/assets/5753046/7953511/80dc7784-09e3-11e5-8cea-5e5e1c36671c.png)

**Comment by joaomlopes** [comment]
@balvirsingh Did you manage to solve this error?

**Comment by stedekay** [comment]
Sorry that I never answered anymore to this issue.
This library was maintained poorly by me the last couple years due to spending less time for Open Source, more for my family (and this priority will also exist in the future).

If this issue still exists, please open a new issue and I will try my best to help out.
