### ISSUE TITLE
Doesn't work with Cyrillic symbols?

### ISSUE THREAD

**Issue by AlexanderMatveev** [stedekay/SpraedPDFGeneratorBundle#26]
Looks like Cyrillic symbols are not supported?
Everything is printed successfully, except Cyrillic symbols.

**Comment by alexmatveev** [comment]
Any support please?

**Comment by stedekay** [comment]
Sorry that I never answered anymore to this issue.
This library was maintained poorly by me the last couple years due to spending less time for Open Source, more for my family (and this priority will also exist in the future).

If this issue still exists, please open a new issue and I will try my best to help out.
