### ISSUE TITLE
Add bookmarks to the PDF

### ISSUE THREAD

**Issue by ftesone** [stedekay/SpraedPDFGeneratorBundle#28]
Is there a way to add or define bookmarks to the PDF file?
I've tried adding to the `<head>`, as seen [here](https://code.google.com/p/flying-saucer/wiki/HowTo_PDF_bookmarks_from_xhtml_markup)

``` xml
<bookmarks>
    <bookmark name="something1" href="#something1" />
    <bookmark name="something2" href="#something2" />
</bookmarks>
```

but throws the error

```
The exit status code '1' says something went wrong:
stderr: "linea 53 columna 5 -Error:<bookmarks> no se reconoce!
linea 54 columna 9 -Error:bookmark no se reconoce!
linea 55 columna 9 -Error:bookmark no se reconoce!
linea 56 columna 9 -Error:bookmark no se reconoce!
```

Note: _no se reconoce_ means _unrecognized_

**Comment by stedekay** [comment]
Sorry that I never answered anymore to this issue.
This library was maintained poorly by me the last couple years due to spending less time for Open Source, more for my family (and this priority will also exist in the future).

If this issue still exists, please open a new issue and I will try my best to help out.
