### ISSUE TITLE
Images are not included

### ISSUE THREAD

**Issue by inmarelibero** [stedekay/SpraedPDFGeneratorBundle#29]
The generation of the pdf goes well, but no images are included.

The image is included with:

`<img src='https://gogobus.it/images/email/logo-gogobus.png' width="192" height="40" border='0' alt="gogobus" />`

and the image exists on the remote server. any advice? thanks

**Comment by pierred69** [comment]
Same problem but for a css background-image property (full qualified image url too)

**Comment by stedekay** [comment]
Sorry that I never answered anymore to this issue.
This library was maintained poorly by me the last couple years due to spending less time for Open Source, more for my family (and this priority will also exist in the future).

If this issue still exists, please open a new issue and I will try my best to help out.
