### ISSUE TITLE
headers

### ISSUE THREAD

**Issue by vodoo22** [stedekay/SpraedPDFGeneratorBundle#30]
hey please i need to know how to enable headers, would u provide example for that?, thx

**Comment by chrislebaron** [comment]
@vodoo22, I know it's been a long time since you posted, but were you able to figure this out?

**Comment by stedekay** [comment]
Sorry that I never answered anymore to this issue.
This library was maintained poorly by me the last couple years due to spending less time for Open Source, more for my family (and this priority will also exist in the future).

If this issue still exists, please open a new issue and I will try my best to help out.
