### ISSUE TITLE
No config possibility for tmp directory and java "command"

### ISSUE THREAD

**Issue by nixoschu** [stedekay/SpraedPDFGeneratorBundle#32]
Currently I need to install one of my projects on a shared host. The user I can use has no permissions to write into **/tmp** which is the directory returned by _sys_get_temp_dir_ used in _createTemporaryFile()_ in PDFGenerator.php

It would be nice if there was a simple config or some parameters that would be used to determine the temp directory that will be used.

```
if (is a tmp dir configured ?) {
    use this dir
} else {
    use sys_get_temp_dir
}
```

Same for the actual java "command". It would be nice if you could determine the path to the java executable in a config or by using a parameter.

**Comment by stedekay** [comment]
Sorry that I never answered anymore to this issue.
This library was maintained poorly by me the last couple years due to spending less time for Open Source, more for my family (and this priority will also exist in the future).

If this issue still exists, please open a new issue and I will try my best to help out.
